# Ejercicios Numpy II

## Ejercicio 1
1. Crea un array que vaya del 0 al 9 y que se llame `my_array`
2. Imprime por pantalla los elementos [9 7 5 3 1] en ese orden.

In [7]:
import numpy as np

my_array = np.arange(10)
print(my_array[: : -2])

[9 7 5 3 1]


## Ejercicio 2
Imprime por pantalla la secuencia [[8 7]] del array `my_array`

In [13]:
print(my_array[8:6:-1])

[8 7]


## Ejercicio 3
Imprime por pantalla la secuencia [[2 1 0]] de `my_array`

In [15]:
print(my_array[2::-1])

[2 1 0]


## Ejercicio 4
1. Crea una matriz de 4x5, con una secuencia del 1 al 20
2. Invierte totalmente la matriz. Tanto las filas, como las columnas

In [23]:
myseq = np.arange(1, 21)
myseq = myseq.reshape(4, 5)
myseq = np.flip(myseq)
myseq

array([[20, 19, 18, 17, 16],
       [15, 14, 13, 12, 11],
       [10,  9,  8,  7,  6],
       [ 5,  4,  3,  2,  1]])

## Ejercicio 5

Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[1, 2],
       [6, 7]])
```

In [25]:
newa = np.flip(myseq[2: , 3:])
newa

array([[1, 2],
       [6, 7]])

## Ejercicio 6
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[ 1,  3,  5],
       [11, 13, 15]])
```

In [28]:
newb = myseq[3::-2, ::-2]
newb

array([[ 1,  3,  5],
       [11, 13, 15]])

## Ejercicio 7
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[ 5,  4,  3,  2,  1],
       [10,  9,  8,  7,  6],
       [15, 14, 13, 12, 11]])
```

In [38]:
newc = myseq[-1:0:-1]
newc

array([[ 5,  4,  3,  2,  1],
       [10,  9,  8,  7,  6],
       [15, 14, 13, 12, 11]])

## Ejercicio 8
Dado el siguiente array:

```Python
x = np.array(["Loro", "Perro", "Gato", "Loro", "Perro"])
```

Filtra el array para quedarte únicamente con los loros.

Resuélvelo de dos maneras diferentes

In [68]:
x = np.array(["Loro", "Perro", "Gato", "Loro", "Perro"])

y = (x[0] + " " + x[3])
print(y)
z = [] #aunque se quedaria en una lista normal
for x in x:
    if x == "Loro":
        z.append(x)

print(z)

filter_arr = x ="Loro"
print(filter_arr)

t=""
for i in x:
    if x == "Loro":
        t = t + x + " " 

print("t =",t) # no entiendo que esta pasando aqui para nada, for i in x, if X == Loro

Loro Loro
['Loro', 'Loro']
Loro
t = Loro Loro Loro Loro 


## Ejercicio 9
Crea una secuencia de 20 elementos y transformala en un array compuesto por 2 matrices de 5x2

In [70]:
xet = np.arange(20)
xet = xet.reshape(2, 5, 2)
xet

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]]])

## Ejercicio 10
Obtén el siguiente array, partiendo de la matriz del **ejercicio 4**
```Python
array([[20, 19, 18, 17, 16],
       [15, 14, 13, 12, 11],
       [10,  9,  8,  7,  6],
       [ 5,  4,  3,  2,  1]])
```

In [71]:
print(myseq)

[[20 19 18 17 16]
 [15 14 13 12 11]
 [10  9  8  7  6]
 [ 5  4  3  2  1]]


## Ejercicio 11
Crea un array de 10 0s. ¿Cuánto ocupa en memoria?

Sustituye el 4to elemento por 1, e imprime el array por pantalla

In [75]:
bex = np.zeros(10)
bex

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [78]:
n = np.zeros(10)
print(n)
print("%d bytes" % (n.size * n.itemsize))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
80 bytes


## Ejercicio 12
Crea un vector que vaya del 10 al 49

Inviértelo

In [80]:
vec = np.flip(np.arange(10, 50))
print(vec)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


## Ejericio 13
Encuentra los indices de los valores que no sean 0 del siguiente vector [[1,2,0,0,4,0]]. El output sería [[0, 1, 4]]. [Encuentra el método apropiado en la documentación.](https://numpy.org/doc/)

In [90]:
vec1 = ([1,2,0,0,4,0])



In [92]:
g = vec1 != 0
g

True

In [93]:
g = [i for i in range(len(vec1)) if vec1[i] > 0]
g

[0, 1, 4]

In [ ]:
>>> b = y > 20
>>> b
array([[False, False, False, False, False, False, False],
      [False, False, False, False, False, False, False],
      [False, False, False, False, False, False, False],
      [ True,  True,  True,  True,  True,  True,  True],
      [ True,  True,  True,  True,  True,  True,  True]])
>>> y[b[:,5],1:3]
array([[22, 23],
       [29, 30]])


## Ejercicio 14
Crea una matriz de numeros aleatorios 10x10. Encuentra los valores mínimo y máximo.

In [101]:
import random

h = np.random.randint(100, size=(10, 10))
print(h)
print("Min:", np.amin(h))
print("Max:",np.amax(h))

[[31 53 57 33 37  3 46 73 70 43]
 [94 51 76 49 79 86 21 46  6 68]
 [24 64 17 51 12 57 42  9  3 26]
 [20 66 45 72 17 81 47 59  5 39]
 [20 47 44 17 30 81 94 45 68 81]
 [26 52 77 66 74 88 46 98 26  5]
 [81 24 49  5 13 70 66 32 66  2]
 [22 60 48 11 85 66 72 20 46 90]
 [17 78 68 54  1  1  5 91 16 12]
 [96 42 85 88 13 44 32 12 79 43]]
Min: 1
Max: 98


## Ejercicio 15
Crea un vector aleatorio de tamaño 30 y calcula su media

In [104]:
jh = np.random.randint(30, size=30)
print(jh)
print("Mean:", np.mean(jh))

[22 14 19 23 18  3 13  7  7  7 19  4 23 24 13 27 27 19  7  7  9 27 11  7
  1 15 11  5 21  8]
Mean: 13.933333333333334


## Ejercicio 16
Crea un array cuadrado de 2D, con las dimensiones que quieras, pero que todo el borde esté compuesto por 1s, y el interior por 0s

In [109]:
x = np.random.randint(1, 2, size=(10, 10))
x[1:-1,1:-1] = 0
print(x)

[[1 1 1 1 1 1 1 1 1 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 1 1 1 1 1 1 1 1 1]]


## Ejercicio 17
Crea una matriz de 8x8, y rellénala con 0s y 1s. Tienes que replicar:
```Python
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
```

In [147]:
hjh = np.random.randint(1, 2, size=(8, 8))
hjh[0::2, ::2] = 0
print(hjh) #no encuentro como invertirlo en cada fila

[[0 1 0 1 0 1 0 1]
 [1 1 1 1 1 1 1 1]
 [0 1 0 1 0 1 0 1]
 [1 1 1 1 1 1 1 1]
 [0 1 0 1 0 1 0 1]
 [1 1 1 1 1 1 1 1]
 [0 1 0 1 0 1 0 1]
 [1 1 1 1 1 1 1 1]]


## Ejercicio 18
Replica la matriz del apartado anterior, pero en este caso usando [la función `tile`](https://numpy.org/doc/stable/reference/generated/numpy.tile.html)

In [160]:
abc = np.array([[1, 0], [0, 1]])
abc = np.tile(abc, (4, 4))
abc

array([[1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1]])

## Ejercicio 19
Crea una matriz aleatoria de 5x5 y normaliza sus valores. Para normalizar tienes que restar sus valores por la media(`np.mean`) y dividir el resultado por la desviación estándar(`np.std`).

In [168]:
fin = np.random.randint(100, size=(5, 5))
print(fin)
norm = np.mean(fin)
print(norm)
torn = np.std(fin)
print(torn)


[[ 4 28 12 81 57]
 [35 50 71  4 29]
 [22 92 27 58 19]
 [78 76 77 72 48]
 [51 98 25 15 73]]
48.08
28.03415060243488


In [171]:
print(fin)
print("--------")
asd = np.linalg.norm(fin)
normal_array = fin/asd

print(normal_array)

[[ 4 28 12 81 57]
 [35 50 71  4 29]
 [22 92 27 58 19]
 [78 76 77 72 48]
 [51 98 25 15 73]]
--------
[[0.01437399 0.10061793 0.04312197 0.29107328 0.20482935]
 [0.12577241 0.17967487 0.25513831 0.01437399 0.10421142]
 [0.07905694 0.33060176 0.09702443 0.20842285 0.06827645]
 [0.28029279 0.2731058  0.2766993  0.25873181 0.17248787]
 [0.18326836 0.35216274 0.08983743 0.05390246 0.26232531]]


## Ejercicio 20
1. Crea una secuencia de números que vayan del 0 al 10.
2. Crea un nuevo array, que parta del anterior, pero sustituya todos los elementos entre el 3 y el 8, por el valor -1
3. Crea un nuevo array que niegue todos los elementos entre el 3 y el 8

In [191]:
fg = np.arange(11)
print(fg)
fg[(fg > 3) & (fg < 8)] = -1
print(fg)
gh = [i for i in range(len(fg)) if fg[i] >= 0]
print(gh)



[ 0  1  2  3  4  5  6  7  8  9 10]
[ 0  1  2  3 -1 -1 -1 -1  8  9 10]
[0, 1, 2, 3, 8, 9, 10]


## Ejercicio 21 
#### Bonus track. Mini hundir la flota para ir practicando.
##### Te ayudará a entender la lógica de la tarea Hundir la Flota.
1. Crea un tablero de 10x10 relleno del carácter espacio ( ).
2. Posiciona un par de barcos en [(0,1), (1,1)] y [(1,3), (1,4), (1,5), (1,6)]. Los barcos serán Os mayúsculas. Como ves, un barco de dos posiciones de eslora y otro de cuatro.
3. Recibe un disparo en uno de los barcos, sustituyendo la O por una X
4. Recibe un disparo en agua, sustituyendo uno de los espacios por un guión: -
5. Ignorando los disparos recibidos, ahora prueba a posicionar otro barco de 4 posiciones dentro del tablero, pero **de manera ALEATORIA.**

**TIP apartado 5**: El barco tendrá una posición inicial aleatoria dentro del tablero, y una orientación también aleatoria (N,S,E,O).

Por ejemplo, si tu posicion inicial fuese (5,0) y la orientación O, no podrias ponerlo porque se sale del tablero. Ahora bien, si fuese orientación este, si podrías, y ocuparía las posiciones [(5,0), (5,1), (5,2), (5,3)]. Por tanto tendrás que iterar con un bucle si es posible encajar el barco en el tablero, y el bucle terminará cuando lo consigas encajar. **Ojo con las posiciones donde ya hay barco!!!**

Usa `import random` para elegir las coordenadas aleatorias.

In [239]:
sea = np.array(" ")
sea = np.tile(sea, (10, 10))
print(sea)

#Crea un tablero de 10x10 relleno del carácter espacio ( ).

[[' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']]


In [240]:
sea[0,1] = "O"
sea[1,1] = "O"
sea[1,3] = "O"
sea[1,4] = "O"
sea[1,5] = "O"
sea[1,6] = "O"
print(sea)

#Posiciona un par de barcos en (0,1), (1,1) y (1,3), (1,4), (1,5), (1,6). Los barcos serán Os mayúsculas. Como ves, un barco de dos posiciones de eslora y otro de cuatro.

[[' ' 'O' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' 'O' ' ' 'O' 'O' 'O' 'O' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']]


In [241]:
sea[1,1] = "X"
print(sea)
#Recibe un disparo en uno de los barcos, sustituyendo la O por una X

[[' ' 'O' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' 'X' ' ' 'O' 'O' 'O' 'O' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']]


In [249]:
sea[4, 4] = "-"
print(sea)
#Recibe un disparo en agua, sustituyendo uno de los espacios por un guión: -

[[' ' 'O' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' 'X' ' ' 'O' 'O' 'O' 'O' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' '-' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']]


In [306]:
posiciones_con_barcos = np.argwhere((sea == "O") | (sea == "X"))
print(posiciones_con_barcos)

#Ignorando los disparos recibidos, ahora prueba a posicionar otro barco de 4 posiciones dentro del tablero, pero de manera ALEATORIA.


[[0 1]
 [1 1]
 [1 3]
 [1 4]
 [1 5]
 [1 6]]


In [380]:
from random import choice

number_of_rows = sea.shape[0]
direction = ["N", "W", "S", "E"]
posposi = ([])
jobdone = 1
#while jobdone == 1:
random_indices = np.random.choice(number_of_rows, size=None, replace=False)
random_indices2 = np.random.choice(number_of_rows, size=None, replace=False)
randgen = np.array([random_indices, random_indices2])
if sea[random_indices, random_indices2] == " ":
    choicedir = choice(direction)
    print(randgen)
    print(choicedir)
    if choicedir== "N":
        posposi.append(randgen)
        
# me falta bastante tiempo para poder encontrar la forma de verificar cada intento dentro de parametros que no tenga barco, no sale del tablero, y ademas en 4 direcciones


[7 0]
W
